import '@/styles/global.scss'

import type { Metadata } from 'next'
import { Roboto, Yellowtail, Open_Sans } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--roboto',
  fallback: ['sans-serif'],
})
export const yellowTail = Yellowtail({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--yellowtail',
  fallback: ['cursive'],
})
export const openSans = Open_Sans({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--open_sans',
  fallback: ['sans-serif'],
})
const typograpy = `${roboto.variable} ${yellowTail.variable} ${openSans.variable}`

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={typograpy}>{children}</body>
    </html>
  )
}
